### ISSUE TITLE
Not really an issue but

### ISSUE THREAD

**Issue by neocvera** [RndMnkIII/PocketAlphaMission#1]
Mac user here so had to make some tweaks to your script to make things a bit easier.
1. need to download the Darwin version of 'orca' for Mac users
2. drop 'orca' in your /tools with the script 
3. open new terminal at folder /tools
4. execute script

#!/usr/bin/env bash

CORE="alphamission"
PARENT=$(dirname "$PWD")
XML="$PARENT/xml"
ROMS="$PARENT/roms"
ASSETS="$PARENT/Assets/$CORE/common"
ORCA="$PARENT/tools/orca"

echo "Current working directory: $PWD"
echo "XML directory: $XML"

find "$XML" -name '*.mra' | while read -r line; do
    echo "Processing file '$line'"
    "$ORCA" -z "$ROMS" -O "$ASSETS" "$line"
done

echo "Processing complete!"

exit 0

**Comment by RndMnkIII** [comment]
I have included the orca.exe executable because I only have a Windows computer to test the tool, I have not been able to test it on a Mac, in any case, on the website of this tool there are instructions for different systems including Macs, be guided by those instructions .
