### ISSUE TITLE
Wrong resolution in dock

### ISSUE THREAD

**Issue by hgage2003** [RndMnkIII/PocketAlphaMission#2]
It looks like left and right sides trimmed a bit in dock mode. Around 10 pixels, I think. I can submit photo, if it will help.

**Comment by RndMnkIII** [comment]
Yes,  send a photo please

**Comment by RndMnkIII** [comment]
I changed the aspect ratio for best fit 4:3 screen in vertical mode from 4:3 to 5:3 could be related to this but send image to see

**Comment by RndMnkIII** [comment]
could yo tell me more details about the rotation mode and about the screen used: model, resolution used,...

**Comment by hgage2003** [comment]
I use dock 1080p 60hz resolution. I can check all other too (480 and 720p). Tis shots was made with capture card, but picture looks the same on 4k OLED tv. 
![2023111814322269](https://github.com/RndMnkIII/PocketAlphaMission/assets/14826472/e1db0ff5-1f0a-4542-890f-2ea2c8ea286e)
![2023111814322520](https://github.com/RndMnkIII/PocketAlphaMission/assets/14826472/0cc1a06b-5734-4b0d-8a1c-2d98b8fac93b)
![2023111814323494](https://github.com/RndMnkIII/PocketAlphaMission/assets/14826472/21fcd21e-6b88-456e-9c62-f24852b0b0ea)

**Comment by hgage2003** [comment]
I captured the end of demo mode, where you can see ship part in top left corner of the screen with all available resolutions and made a screenshot with memories on undocked pocket:
![480p_dock](https://github.com/RndMnkIII/PocketAlphaMission/assets/14826472/1e9cb25e-3280-4446-bfca-2386e1a1651d)
![720p_dock](https://github.com/RndMnkIII/PocketAlphaMission/assets/14826472/a1063755-987f-454d-bfe9-54b035a1ab91)
![1080p_dock](https://github.com/RndMnkIII/PocketAlphaMission/assets/14826472/52341ba8-3a75-4568-983e-56511bd106c3)
![pocket_undocked](https://github.com/RndMnkIII/PocketAlphaMission/assets/14826472/dc0efdda-67ca-4cb5-a196-26489344a3b8)

Looks like only left part is cropped.

**Comment by hgage2003** [comment]
> I captured the end of demo mode, where you can see ship part in top left corner of the screen with all available resolutions and with undocked pocket: ![480p_dock](https://user-images.githubusercontent.com/14826472/283996613-1e9cb25e-3280-4446-bfca-2386e1a1651d.png) ![720p_dock](https://user-images.githubusercontent.com/14826472/283996615-a1063755-987f-454d-bfe9-54b035a1ab91.png) ![1080p_dock](https://user-images.githubusercontent.com/14826472/283996616-52341ba8-3a75-4568-983e-56511bd106c3.png) ![pocket_undocked](https://user-images.githubusercontent.com/14826472/283996617-dc0efdda-67ca-4cb5-a196-26489344a3b8.png)
> 
> Looks like only left part is cropped.
> 
> Now I'll try your new aspect ratio settings

**Comment by hgage2003** [comment]
> could yo tell me more details about the rotation mode and about the screen used: model, resolution used,...

I think dock have no rotation modes. At least I can not find them. Only available screen modes are 480p/720p/1080p in 50 and 60hz

**Comment by RndMnkIII** [comment]
Can you edit /Cores/RndMnkIII.alphamission/video.json:
Play with this integer values that build Up the aspect ratio, find the pair that BEST fit your screen:
aspect_w, aspect_h, try It: 4/3,5/3,6/3,4/4...

**Comment by RndMnkIII** [comment]
In my  1020x1080 TV setup for example with the Dock the imagen is cropped in the top and in the botton with default 90° rotation . On my mini screen 1280x720 Toyo with 5:3 aspecto ratio is Ok

**Comment by RndMnkIII** [comment]
I cannot create a default settings that BEST fit all screens

**Comment by hgage2003** [comment]
> In my 1020x1080 TV setup for example with the Dock the imagen is cropped in the top and in the botton with default 90° rotation . On my mini screen 1280x720 Toyo with 5:3 aspecto ratio is Ok

This could be tv cropping (and usually can be turned off in tv menu). Have your dock different output resolutions than mine? Dock renders 1920x1080 regardless of screen you use.

Is the native resolution for game 216x288 with square pixels? It looks it must be 3x4 then

I'll try to edit video.json and see

**Comment by hgage2003** [comment]
Ok, I left only one scaler mode, set it to 5x3 (and 8x3, 8x4) and see the same picture: although aspect ratio become more narrow, exact 8 first pixels on the screen is not shown in dock mode. It is obviously a bug in rendering, maybe its on analogue side, I don't know

![2023111817364035](https://github.com/RndMnkIII/PocketAlphaMission/assets/14826472/52f3d8a7-412d-4443-8dfe-0296be3b7e5b)

**Comment by RndMnkIII** [comment]
I think that IS related to your TV set, Sorry butbI'm limited that Pocket video.json settings

**Comment by hgage2003** [comment]
How can it be related to my tv set, if I send you screensots from avermedia capture card? And it looks absolutely identical to my tv picture.

Pocket dock outputs 1080p picture and there is missing data on this picture, regardless of video.json settings. If your dock shows ship part pickup in the end of demo in full, not just right part of it, it could be my dock or pocket problem. Can you check this ship part on your dock output? It full sprite must be seen on screen:
![1080p_dock_1](https://github.com/RndMnkIII/PocketAlphaMission/assets/14826472/7ff77673-810d-4a62-9117-73d2b709fc7b)

**Comment by hgage2003** [comment]
I've found rotation settings in core, I think problem is there. 
When I set rotation in dock mode to 0 or 180 degrees, i see full picture. In 90 and 180 first 8 columns of pixels is not drawn at all.

But! It works opposite in pocket mode (without dock) - in 0 and 180 rotation the same 8 pixel column absent on pockets screen. 

Regardless of rotation it is the same pixels left of energy bar

**Comment by hgage2003** [comment]
It really looks like analogue scaler problem. When you make screenshot, all picture is here.
